image: node:latest

stages:
- test
- publish

cache:
  paths:
  - node_modules

before_script:
- git submodule sync --recursive
- git submodule update --init --recursive
- npm install
- npm run bootstrap

.build-deploy:
  before_script:
  - npm run setup-ssh
  - npm run setup-git
  - npm run build

.build-test:
  before_script:
  - npm run build

test:
  extends: .build-test
  stage: test
  script:
  - npm run ci-test

prerelease:
  extends: .build-deploy
  stage: publish
  only:
  - develop
  script:
  - npm run pre-release

release:
  extends: .build-deploy
  stage: publish
  only:
  - master
  script:
  - npm run release
