image: node:latest

stages:
- test
- publish

before_script:
- git submodule sync --recursive
- git submodule update --init --recursive
- npm install
- npm run bootstrap
- git remote get-url origin

cache:
  paths:
  - node_modules

continuous:
  stage: test
  except:
  - develop
  - master
  script:
  - npm run build
  - npm run ci-test
  - npm run canary

prerelease:
  stage: publish
  only:
  - develop
  script:
  - npm run build
  - npm run ci-test
  - npm run pre-release

release:
  stage: publish
  only:
  - master
  script:
  - npm run build
  - npm run ci-test
  - npm run release
