image: node:latest

stages:
- test
- publish

before_script:
- git submodule sync --recursive
- git submodule update --init --recursive
- npm install
- npm run bootstrap

cache:
  paths:
  - node_modules

continuous:
  stage: test
  except:
  - develop
  - master
  script:
  - npm run build
  - npm run ci-test
  - npm run canary

prerelease:
  stage: publish
  only:
  - develop
  script:
  - npm run setup-ssh
  - npm run setup-git
  - npm run build
  - npm run ci-test
  - npx lerna publish --yes

release:
  stage: publish
  only:
  - master
  script:
  - npm run setup-ssh
  - npm run setup-git
  - npm run build
  - npm run ci-test
  - npm run release
