image: node:latest

# Anchors
#-------------------------------------------------------------------------------
.build:
  script:
  - npm run build

.publish:
  script:
  - npm run setup-ssh
  - npm run setup-git
  - npm run build

# Pipeline
#-------------------------------------------------------------------------------
stages:
- test
- publish

before_script:
- git submodule sync --recursive
- git submodule update --init --recursive
- npm install
- npm run bootstrap

cache:
  paths:
  - node_modules

test:
  extends: .build
  stage: test
  script:
  - npm run ci-test

prerelease:
  extends: .publish
  stage: publish
  only:
  - develop
  script:
  - npm run pre-release

release:
  extends: .publish
  stage: publish
  only:
  - master
  script:
  - npm run release
