image: node:latest

stages:
- test
- publish

before_script:
- source .ci-env
- git submodule update --init --recursive
- npm ci
- npm run bootstrap
- npm run configure:ssh

cache:
  paths:
  - node_modules

feature:
  stage: test
  only:
  - /feature\/.*/
  script:
  - npm run build:ci
  - npm run test:ci
  - npm run release:canary

prerelease:
  stage: publish
  only:
  - develop
  script:
  - npm run configure:git
  - npm run build:ci
  - npm run test:ci
  - npm run release:pre

release:
  stage: publish
  only:
  - master
  script:
  - npm run configure:git
  - npm run build:ci
  - npm run test:ci
  - npm run release
