image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules

publish: &publish
  script:
    - npm run setup-git
    - npm run build

before_script:
  - npm install
  - npm run bootstrap
  - npm run setup-ssh

test:
  stage: test
  script:
    - npm test

prerelease:
  <<: *publish
  stage: publish
  only:
    - develop
  script:
    - npm run pre-release

release:
  <<: *publish
  stage: publish
  only:
    - master
  script:
    - npm run release
