image: node:latest

stages:
  - merge
  - publish

before_script:
  - git submodule update --init --recursive
  - source .ci-env
  - npm ci
  - npm run configure:ssh
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

cache:
  paths:
    - node_modules

merge:
  stage: merge
  only:
    - merge_request
  script:
    - npm run build:ci
    - npm run test:ci

continuous:
  stage: publish
  only:
    - /feature\/.*/
    - /hotfix\/.*/
  script:
    - npm run build:ci
    - npm run test:ci
    - npm run release:canary

prerelease:
  stage: publish
  only:
    - develop
  script:
    - npm run configure:git
    - npm run build:ci
    - npm run test:ci
    - npm run release:pre

release:
  stage: publish
  only:
    - master
  script:
    - npm run configure:git
    - npm run build:ci
    - npm run test:ci
    - npm run release
