image: node:latest

stages:
  - merge
  - publish

before_script:
  - git submodule update --init --recursive
  - source .ci-env.sh
  - npm ci
  - npm install -g lerna
  - npm run configure:ssh
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

cache:
  paths:
    - node_modules

merge:
  stage: merge
  except:
    - tags
  only:
    - merge_request
  script:
    - npm run build:ci
    - npm run test:ci
  variables:
    NODE_ENV: "test"

continuous:
  stage: publish
  except:
    - tags
  only:
    - /feature\/.*/
    - /hotfix\/.*/
  script:
    - npm run build:ci
    - npm run test:ci
    - npm run release:canary
  variables:
    NODE_ENV: "test"

prerelease:
  stage: publish
  except:
    - tags
  only:
    - develop
  script:
    - npm run configure:git
    - npm run build:ci
    - npm run test:ci
    - npm run release:pre
  variables:
    NODE_ENV: "development"

release:
  stage: publish
  except:
    - tags
  only:
    - master
  script:
    - npm run configure:git
    - npm run build:ci
    - npm run test:ci
    - npm run release
  variables:
    NODE_ENV: "production"
