image: node:latest

# Anchors
#-------------------------------------------------------------------------------
.base:
  before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - npm install
  - npm run bootstrap

.build:
  extends: .base
  before_script:
  - npm run build

.build-publish:
  extends: .base
  before_script:
  - npm run setup-ssh
  - npm run setup-git
  - npm run build

# Pipeline
#-------------------------------------------------------------------------------
stages:
- test
- publish

cache:
  paths:
  - node_modules

test:
  extends: .build
  stage: test
  script:
  - npm run ci-test

prerelease:
  extends: .build-publish
  stage: publish
  only:
  - develop
  script:
  - npm run pre-release

release:
  extends: .build-publish
  stage: publish
  only:
  - master
  script:
  - npm run release
