image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules

before_script:
  - npm install
  - npm run bootstrap
  - npm run setup-ssh

test:
  stage: test
  script:
    - npm test

pre-publish:
  stage: publish
  only:
    - develop
  script:
    - npm run setup-git
    - npm run build
    - npm run prerelease

publish:
  stage: publish
  only:
    - master
  script:
    - npm run setup-git
    - npm run build
    - npm run release
