image: node:latest

stages:
  - test
  - publish

cache:
  paths:
    - node_modules

before_script:
  - npm install
  - ./node_modules/.bin/git-ssh-key setup
  - ssh-keyscan git.nativecode.net >> ~/.ssh/known_hosts

test:
  stage: test
  script:
    - ./lerna bootstrap
    - npm test

pre-publish:
  stage: publish
  only:
    - develop
  script:
    - ./.ci/setup-git
    - ./lerna bootstrap
    - ./lerna run build
    - ./lerna publish --yes --canary --dist-tag next

publish:
  stage: publish
  only:
    - master
  script:
    - ./.ci/setup-git
    - ./lerna --version
    - ./lerna bootstrap
    - ./lerna run build
    - ./lerna publish from-package --yes --dist-tag latest
