image: node:latest

stages:
- test
- publish

cache:
  paths:
  - node_modules

before_script:
- git submodule sync --recursive
- git submodule update --init --recursive
- npm install
- npm run bootstrap
- npm run setup-ssh

test:
  stage: test
  script:
  - npm run ci-test

prerelease:
  stage: publish
  only:
  - develop
  script:
  - npm run setup-git
  - npm run build
  - npm run pre-release

release:
  stage: publish
  only:
  - master
  script:
  - npm run setup-git
  - npm run build
  - npm run release
