#!/bin/bash

set -e

MODE=$1
LERNA=./node_modules/.bin/lerna

case $MODE in
"canary")
    ${LERNA} publish --canary
    ;;
"release")
    ${LERNA} publish from-git --create-release gitlab --dist-tag latest
    ;;
"prerelease")
    ${LERNA} version prerelease --dist-tag next --preid next
    ${LERNA} publish from-git --dist-tag next
    ;;
esac
