#!/bin/bash

set -e

MODE=$1
LERNA=./node_modules/.bin/lerna

case $MODE in
"canary")
    ${LERNA} publish --conventional-commits --canary --preid canary
    ;;
"release")
    ${LERNA} version --conventional-commits --conventional-graduate
    ${LERNA} publish  --conventional-commits --create-release gitlab
    ;;
"prerelease")
    ${LERNA} version prerelease --conventional-commits --dist-tag next --preid next --no-changelog
    ${LERNA} publish  --conventional-commits --dist-tag next
    ;;
esac
